var RulesEditorConstants = {
    RULESEDITOR_FETCHRULES: "RULESEDITOR_FETCHRULES",
    RULESEDITOR_FETCHNEWRULE: "RULESEDITOR_FETCHNEWRULE",
    RULESEDITOR_SAVE: "RULESEDITOR_SAVE",
    RULESEDITOR_DELETERULE: "RULESEDITOR_DELETERULE",
    RULESEDITOR_SELECTRULE: "RULESEDITOR_SELECTRULE",
    RULESEDITOR_STARTNEWRULE: "RULESEDITOR_STARTNEWRULE"
};